print("Masukkan Nilai Sisi Atas")
atas = int(input())
print("Masukkan Nilai Sisi Bawah")
bawah = int(input())
print("Masukkan Nilai Sisi Kiri")
kiri = int(input())
print("Masukkan Nilai Sisi Kanan")
kanan = int(input())
keliling = atas + bawah + kiri + kanan
print("Jumlah Keliling dari Bangun Datar Trapesium Adalah: " + str(keliling))
print("Menghitung Luas Trapesium")
print("Masukkan Nilai Tinggi")
tinggi = int(input())
luas = float(atas + bawah) / 2 * tinggi
print("Luas Dari Bangun Datar Trapesium Adalah: " + str(luas))
